### PR TITLE
Main.css style

### PR DESCRIPTION
**Pull request by yannickvdthoren**
You can see and try the style here : http://dev.yannickvdthoren.com

### CODE REVIEW

**Comment by johnroper100** [comment]
That looks good, could you maybe make the copyright message smaller? It doesn't have to be a lot, but it seems to be almost as big as a post header.

**Comment by yannickvdthoren** [comment]
And that's done ! ;)

**Comment by johnroper100** [comment]
Also, could you maybe try to create a second sheet, not to actually use, but to test that a user could create their own alternative using the same markup? I'd like the theming be done in a CSS zen garden way: the same markup, different CSS.

**Comment by yannickvdthoren** [comment]
I'll try that ! Maybe we'll have to make a list with the markup...

**Comment by johnroper100** [comment]
Please make sure that there is styling for:

- h1
- h2
- h3
- h4
- h5
- a
- code
- hr
- img
- quote

**Comment by semioticrobotic** [comment]
I'm not sure if it's useful to you, @yannickvdthoren, but I maintain [a fairly minimalistic fork of Dropplets' original "simple" theme](https://github.com/semioticrobotic/semioticrobotic.net/tree/master/simple) that might actually serve as a reasonable guide to styling (simply because it's so spartan). Have a look if you'd like.

**Comment by yannickvdthoren** [comment]
@semioticrobotic I'll take a look at this ! ;)

@johnroper100 Do you have a doc for the Markdown used in Dropplets ?

**Comment by johnroper100** [comment]
These are the currently supported markdown elements and the tags they generate:

- headers (h1,h2,h3,h4,h5)
- links (a)
- ul lists (ul, li)
- bold (strong)
- empasis (em)
- del (del)
- quote (q)
- inline code (code)
- ol lists (ol, li)
- blockquotes (blockquote)
- horizonal rule (hr)
- paragraph

**Comment by johnroper100** [comment]
The zen looks good. Thanks! I may keep it around just for testing, but it was just to see if it could be done, not actually for release.

**Comment by johnroper100** [comment]
I'm only asking that you go over all the tags, because this is the default stylesheet. It is going to be used by default by everyone who downloads dropplets, so it needs to support anything they may throw at it.

**Comment by yannickvdthoren** [comment]
Are they ? Or do you want them centered ?

**Comment by johnroper100** [comment]
In the post content, Hs should be left aligned. They are currently centered.

**Comment by johnroper100** [comment]
The post title should still be centered

**Comment by johnroper100** [comment]
@yannickvdthoren I just tried the zen style on the latest version of Dropplets 2 and posts look like this:

db533650-ec08-4bce-9c89-57133a850bb9

Also, would it be possible to center the footer on the zen style?

**Pull request merged**
