### PR TITLE
2.0 Setup

### PR DESCRIPTION
**Pull request by yannickvdthoren**
I wanted to work a bit on some css today, so I created a new style for the setup.css.
I worked on the wording as well... If you don't like it, you can still use only my css !

I also added a reset.css file that is more efficient than normalize.css and that don't get you a basic style.

You can see the live exemple here : http://dev.yannickvdthoren.com/setup

### CODE REVIEW

**Comment by johnroper100** [comment]
I added some comments. Can you apply this to all pages that use the setup.css?

**Comment by yannickvdthoren** [comment]
I don't see your comment on Github.

Aye aye captain ! I'll apply it !

**Comment by johnroper100** [comment]
The comments are here on this page

**Comment by yannickvdthoren** [comment]
Done !

You'll have to check the wording for each to see what you want to change. And if you notice a style problem, say it !

**Comment by johnroper100** [comment]
I'm committing this now. I'll go back and check for wording later. Thanks! If you'd like, you can also work on the default blog stylesheet in the same style as well. I'd like it to be just text. The style should work based on the minimal markup that is already there. If you need to move things around, that's fine, but I don't want too much more complexity.

**Comment by johnroper100** [comment]
On the post page, the post title input is bolded unlike the others, and the management password input, is out of line with the other form elements.

**Comment by johnroper100** [comment]
On the post page `TIME TO WRITE YOUR PROSE` is not in style.

**Comment by johnroper100** [comment]
as well as `You can personnalise the style of your post here`

**Pull request merged**
