### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by yannickvdthoren**
This should fix the problem.

When you say you want the header to be aligned, where do you want it to be aligned ?

### CODE REVIEW

**Comment by johnroper100** [comment]
The header is fine, can you align the footer to be centered?

**Comment by johnroper100** [comment]
And it looks like you got it already.

**Comment by yannickvdthoren** [comment]
Sorry, the footer. Must be aligned on the page or in the column ?

**Comment by johnroper100** [comment]
Centered on the page

**Pull request merged**
